preset: recommended

risky: false

linting: true

enabled:
  - short_array_syntax
  - unalign_double_arrow

disabled:
  - align_double_arrow
  - long_array_syntax

finder:
  exclude:
    - "tests"
  name:
    - "*.php"
  not-name:
    - "*Stub.php"
  depth:
    - "< 3"
