preset: psr2

risky: false

linting: true

enabled:
  - short_array_syntax
  - unalign_double_arrow

disabled:

finder:
  exclude:
    - "tests"
  name:
    - "*.php"
  not-name:
    - "*Stub.php"
  depth:
    - "< 3"
